In [ ]:
import numpy as np
import pandas as pd


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/laxmimerit/twitter-data/master/twitt30k.csv')
df

twitts  sentiment
0           @robbiebronniman Sounds like a great night.           1
1      Damn the person who stolde my wallet !!!!!  Ma...          1
2      Greetings from the piano bench  (photo) http:/...          1
3      @drewryanscott i love it!! i love you!! haha f...          1
4      @kissthestars Pretty pretty pretty please, pak...          0
...                                                  ...        ...
29995  @Calumfan1 is it in any way related to photosh...          0
29996                   @Swiz_NZ really? wow thats crap           0
29997  At the 2010 lexus HS250h press event.  Again, ...          0
29998  @karmicunderpath ooooh now there's a nice thou...          1
29999  @mariap91 i'd usually ask you about the sun an...          1

[30000 rows x 2 columns]

In [ ]:
df['sentiment'].value_counts()

1    15000
0    15000
Name: sentiment, dtype: int64

In [ ]:
def svm(df):    
    X=df['twitts']
    y=df['sentiment']
    tfidf=TfidfVectorizer()
    X=tfidf.fit_transform(X)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)
    print('Shape of X:',X.shape)
    clf=LinearSVC()
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    print()
    print('Report')
    print(classification_report(y_test,y_pred))
    return [tfidf,clf]

In [ ]:
%%time
l=svm(df)
tfidf=l[0]
clf=l[1]


Shape of X: (30000, 40854)

Report
              precision    recall  f1-score   support

           0       0.75      0.74      0.75      3000
           1       0.74      0.75      0.75      3000

    accuracy                           0.75      6000
   macro avg       0.75      0.75      0.75      6000
weighted avg       0.75      0.75      0.75      6000

CPU times: user 1.29 s, sys: 14.9 ms, total: 1.31 s
Wall time: 1.37 s


In [ ]:
t=['i am very happy']

In [ ]:
clf.predict(tfidf.transform(t))

array([1])

In [ ]:
import re
import os
import sys
import json

import pandas as pd
import numpy as np
import spacy
from spacy.lang.en.stop_words import STOP_WORDS as stopwords
from bs4 import BeautifulSoup
import unicodedata
from textblob import TextBlob
import en_core_web_sm

from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
pip install git+https://github.com/Indeevar1019/preprocess_Indeevar1019.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/Indeevar1019/preprocess_Indeevar1019.git to /tmp/pip-req-build-bce78ezf
  Running command git clone --filter=blob:none --quiet https://github.com/Indeevar1019/preprocess_Indeevar1019.git /tmp/pip-req-build-bce78ezf
  Resolved https://github.com/Indeevar1019/preprocess_Indeevar1019.git to commit 2ed4ea6ef527ca385eae9daf8500c3b8c636854c
  Preparing metadata (setup.py) ... done
  Created wheel for preprocess-Indeevar10: filename=preprocess_Indeevar10-0.0.4-py3-none-any.whl size=3869 sha256=f4619779556763367fb1ecd6efb3d637c87bad3d13c69edf6e8342901c9ff74a
  Stored in directory: /tmp/pip-ephem-wheel-cache-jjfc3rlw/wheels/e8/75/5a/6a0ef2f522c7365b23fc26e7c0765d0c3f06b435d6db8902b6
Successfully built preprocess-Indeevar10


In [ ]:
import preprocess_Indeevar1019 as pp

In [ ]:
df['twitts']=df['twitts'].apply(lambda x: x.lower())

In [ ]:
df['twitts']=df['twitts'].apply(lambda x: pp.cont_exp(x))

In [ ]:
df

twitts  sentiment
0           @robbiebronniman sounds like a great night.           1
1      damn the person who stolde my wallet !!!!!  ma...          1
2      greetings from the piano bench  (photo) http:/...          1
3      @drewryanscott i love it!! i love you!! haha f...          1
4      @kissthestars pretty pretty pretty please, pak...          0
...                                                  ...        ...
29995  @calumfan1 is it in any way related to photosh...          0
29996                   @swiz_nz really? wow thats crap           0
29997  at the 2010 lexus hs250h press event.  again, ...          0
29998  @karmicunderpath ooooh now there is a nice tho...          1
29999  @mariap91 i would usually ask you about the su...          1

[30000 rows x 2 columns]

In [ ]:
svm(df)

Shape of X: (30000, 40846)

Report
              precision    recall  f1-score   support

           0       0.75      0.74      0.75      3000
           1       0.75      0.76      0.75      3000

    accuracy                           0.75      6000
   macro avg       0.75      0.75      0.75      6000
weighted avg       0.75      0.75      0.75      6000



[TfidfVectorizer(), LinearSVC()]

In [ ]:
#remove emails and urls
df['twitts']=df['twitts'].apply(lambda x: pp.remove_emails(x))
df['twitts']=df['twitts'].apply(lambda x: pp.remove_urls(x))
df['twitts']=df['twitts'].apply(lambda x: pp.remove_rt(x))
df['twitts']=df['twitts'].apply(lambda x: pp.remove_html_tags(x))
df['twitts']=df['twitts'].apply(lambda x: pp.remove_special_chars(x))


/usr/local/lib/python3.10/dist-packages/preprocess_Indeevar1019/utils.py:173: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  return BeautifulSoup(x, 'lxml').get_text().strip()


In [ ]:
df

twitts  sentiment
0              robbiebronniman sounds like a great night          1
1      damn the person who stolde my wallet may karma...          1
2                   greetings from the piano bench photo          1
3      drewryanscott i love it i love you haha forget...          1
4      kissthestars pretty pretty pretty please pakid...          0
...                                                  ...        ...
29995    calumfan1 is it in any way related to photoshop          0
29996                      swiz_nz really wow thats crap          0
29997  at the 2010 lexus hs250h press event again can...          0
29998  karmicunderpath ooooh now there is a nice thought          1
29999  mariap91 i would usually ask you about the sun...          1

[30000 rows x 2 columns]

In [ ]:
tfidf,clf=svm(df)

Shape of X: (30000, 42931)

Report
              precision    recall  f1-score   support

           0       0.75      0.74      0.74      3000
           1       0.74      0.75      0.75      3000

    accuracy                           0.75      6000
   macro avg       0.75      0.75      0.75      6000
weighted avg       0.75      0.75      0.75      6000



In [ ]:
clf.predict(tfidf.transform(t))

array([1])

In [ ]:
#Fine tune of our model
def svm(df):    
    X=df['twitts']
    y=df['sentiment']
    tfidf=TfidfVectorizer(norm='l1',ngram_range=(1,2),analyzer='word',max_features=5000)
    X=tfidf.fit_transform(X)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)
    print('Shape of X:',X.shape)
    clf=LinearSVC()
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    #y_train_pred = clf.predict(X_train)
   # y_test_pred = clf.predict(X_test)
    print()
    print('Report')
    print(classification_report(y_test,y_pred))
    predTrain =clf.predict(X_train)
    #accuracy_score(predTrain, trainY)
    training_scores(predTrain, y_train)
    validation_scores(y_test, y_pred)

    return [tfidf,clf]
svm(df)


Shape of X: (30000, 5000)

Report
              precision    recall  f1-score   support

           0       0.75      0.77      0.76      3000
           1       0.77      0.75      0.76      3000

    accuracy                           0.76      6000
   macro avg       0.76      0.76      0.76      6000
weighted avg       0.76      0.76      0.76      6000

Training Scores: Accuracy=0.819
Validation Scores: Accuracy=0.759


[TfidfVectorizer(max_features=5000, ngram_range=(1, 2), norm='l1'),
 LinearSVC()]

NameError: ignored

In [ ]:
import pickle

In [ ]:
pickle.dump(clf,open('clf.pkl','wb'))
pickle.dump(tfidf,open('tfidf.pkl','wb'))

In [ ]:
del clf
del tfidf

In [ ]:
clf=pickle.load(open("clf.pkl","rb"))
tfidf=pickle.load(open("tfidf.pkl",'rb'))

In [ ]:
#tfidf.vocabulary_

In [ ]:
clf.predict(tfidf.transform(t))

array([1])

In [ ]:
#Real time Analysis
consumer_key='i2G667hDxeLXM7f6ZX9rawHH2'
consumer_secret='bGdHjmEQzAsmlSQLxkkSsTspj2a1ey6uYG1vzKaSRr3UoK7NkL'
access_token='772366635122302977-dLcKG9OwVdTu2dt4AbuZcjEs35POYiX'
access_token_secret='Gx0YEjrp75nfIbseFJdbyIuY89W8TchUhUTJOVvz08QBm'
bearer_token='AAAAAAdIa17gV9LO9%2FghNyLNVZ7IGexY%3DIuEQNKGNHdDwg8QBKSCnMUJyvRCovuZc87HH0LluocVdbkVFDa'


In [ ]:
pip install tweepy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/Indeevar1019/preprocess_Indeevar1019.git to /tmp/pip-req-build-u1s_y6cz
  Running command git clone --filter=blob:none --quiet https://github.com/Indeevar1019/preprocess_Indeevar1019.git /tmp/pip-req-build-u1s_y6cz
  Resolved https://github.com/Indeevar1019/preprocess_Indeevar1019.git to commit 2ed4ea6ef527ca385eae9daf8500c3b8c636854c
  Preparing metadata (setup.py) ... done
  Created wheel for preprocess-Indeevar10: filename=preprocess_Indeevar10-0.0.4-py3-none-any.whl size=3869 sha256=d6d438f982f7efc256e2fd68ecb550f8f35ba90fa2948890fe92d6a16205a148
  Stored in directory: /tmp/pip-ephem-wheel-cache-b0ugzrot/wheels/e8/75/5a/6a0ef2f522c7365b23fc26e7c0765d0c3f06b435d6db8902b6
Successfully built preprocess-Indeevar10


In [ ]:
#pip install git+https://github.com/Indeevar1019/preprocess_Indeevar1019.git
import preprocess_Indeevar1019 as pp

In [ ]:
consumer_key = 'R7DGimRNkT11sbngA0MRqLmNE'
consumer_secret = 'w5Axtw43feejwgmPIhqPhPOt1aHso1Guw1yuFwlmijtlh0vguK'
access_token = '1279486577656295425-l3gaKqKuHQdKl44rPXUc0WYcc26wgq'
access_token_secret = '80dGAdcx6LuoWM1mSt669V5NESP0EOuX1dK8Mianjqxi2'

In [ ]:
import tweepy

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
auth.secure = True

public_tweets = api.home_timeline()


In [ ]:
type(public_tweets)

tweepy.models.ResultSet

In [ ]:
new_tweet=public_tweets[0].text

In [ ]:
for tweet in public_tweets:
  print(tweet.text)

Former Vice President #MikePence will officially launch his widely expected campaign for the Republican nomination… https://t.co/D15fAkqUNi
"That '70s Show" star #DannyMasterson was led out in handcuffs from a LA courtroom and could get 30 years to life i… https://t.co/oHUI49P0DE
#BusinessOfSports | In this two-part episode of Business of Sports we spotlight the partnerships and efforts undert… https://t.co/UbjKBKvxwi
Two years after her film "Music" courted controversy for misrepresenting people with #autism, singer-songwriter… https://t.co/p2d8XbFnHr
#JustIn | J.P.Morgan hikes India's FY24 GDP forecast to 5.5%
Catch the day's latest news and updates 📷… https://t.co/RUjNl7Ib23
#ElonMusk has retaken the title of world’s wealthiest person.  The #Tesla Inc. chief executive officer surpassed lu… https://t.co/USMvUhVYz4
RT @ASEANRussia: We congratulate our Indonesian partners and friends on commemorating the Birthday of Pancasila 🇮🇩! https://t.co/Vb67vriFgH
RT @RusEmbUSA: 💬Anatoly Antonov:

In [ ]:
# 
l=[new_tweet]
print(l)
clf.predict(tfidf.transform(l))


['Former Vice President #MikePence will officially launch his widely expected campaign for the Republican nomination… https://t.co/D15fAkqUNi']


array([1])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
file_path='drive/MyDrive/glove.6B.100d.txt'


In [ ]:
data=pd.read_csv('drive/MyDrive/text_to_emotion.csv')

In [ ]:
#Data Preparation
from numpy import array
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix



In [ ]:
data['emotion'].value_counts()

ANGER       5000
FEAR        5000
JOY         5000
LOVE        5000
SADNESS     5000
SURPRISE    5000
Name: emotion, dtype: int64

In [ ]:
%%time
data['text'] = data['text'].apply(lambda x: str(x).lower())
data['text'] = data['text'].apply(lambda x: pp.cont_exp(x))
data['text'] = data['text'].apply(lambda x: pp.remove_special_chars(x))
data['text'] = data['text'].apply(lambda x: pp.remove_accented_chars(x))
# df['text'] = df['text'].apply(lambda x: ps.make_base(x))
# df['text'] = df['text'].apply(lambda x: ps.spelling_correction(x).raw_sentences[0])


CPU times: user 1.04 s, sys: 401 µs, total: 1.04 s
Wall time: 1.14 s


In [ ]:
data['text']

0                                              i feel cold
1                    i feel the cold i can say he sends it
2        i remember feeling like my blood had run cold ...
3        i hate too is stepping outside in the cold and...
4        i do not think i am anti social i just do not ...
                               ...                        
29995    i feel like i am just here watching my body wo...
29996    i am not a person who first created the idea e...
29997    i feel a little surprised as if i don t know w...
29998    i feel like people don t tell me things then a...
29999    i get that old feeling the one where i am not ...
Name: text, Length: 30000, dtype: object

In [ ]:
%%time
#Loading of Glove Vectors
glove_vectors={}
file=open(file_path,encoding='utf-8')
for line in file:
  values=line.split()
  word=values[0]
  vectors=np.asarray(values[1:])
  glove_vectors[word]=vectors
file.close()



CPU times: user 12.8 s, sys: 1.48 s, total: 14.3 s
Wall time: 15.9 s


In [ ]:
len(glove_vectors)

400000

In [ ]:
sample_text=data['text'][0]

In [ ]:
#Text to GLove Vectors
vector_shape=100
def get_vectors(x):
    arr = np.zeros(vector_shape)
    text = str(x).split()
    for t in text:
        try:
            vec = glove_vectors.get(t).astype(float)
            arr = arr + vec
        except:
            pass
    arr = arr.reshape(1, -1)[0]
    return arr/len(text)

In [ ]:
vector=get_vectors(sample_text)
vector

array([-0.267008  ,  0.66335667,  0.73366   , -0.22969   , -0.84137333,
        0.28653667,  0.005435  ,  0.13241333, -0.19898667, -0.34137333,
        0.07526667, -0.112268  ,  0.34247333,  0.09995467,  0.12304333,
       -0.21340833, -0.289818  ,  0.05148667, -0.63726667,  0.13804333,
        0.22524733,  0.87720333, -0.08132627, -0.34913033,  0.09410667,
        0.66297   , -0.274576  , -0.52326333,  0.67806   , -0.25643667,
        0.20968667,  0.67789667,  0.11778   , -0.026936  ,  0.13002667,
        0.335743  , -0.02714667,  0.14828667,  0.61485667, -0.46669333,
       -0.39179   , -0.31825   ,  0.19713667, -0.75069333, -0.16751333,
       -0.16864333,  0.294349  , -0.07035533,  0.34511   , -1.17788667,
        0.170615  , -0.044745  ,  0.15406   ,  0.86005   , -0.07263333,
       -2.42486667,  0.52434667,  0.36412333,  1.22936667,  0.40280967,
        0.15221   ,  1.19223333, -0.90648333, -0.20536323,  0.70086333,
       -0.00429667,  0.76778   ,  0.0281944 , -0.43150333, -0.41

In [ ]:
%%time
data['vec']=data['text'].apply(lambda x: get_vectors(x))

CPU times: user 26.5 s, sys: 68 ms, total: 26.6 s
Wall time: 26.8 s


In [ ]:
data

text   emotion  \
0                                            i feel cold     ANGER   
1                  i feel the cold i can say he sends it     ANGER   
2      i remember feeling like my blood had run cold ...     ANGER   
3      i hate too is stepping outside in the cold and...     ANGER   
4      i do not think i am anti social i just do not ...     ANGER   
...                                                  ...       ...   
29995  i feel like i am just here watching my body wo...  SURPRISE   
29996  i am not a person who first created the idea e...  SURPRISE   
29997  i feel a little surprised as if i don t know w...  SURPRISE   
29998  i feel like people don t tell me things then a...  SURPRISE   
29999  i get that old feeling the one where i am not ...  SURPRISE   

                                                     vec  
0      [-0.26700799999999997, 0.6633566666666666, 0.7...  
1      [-0.22076089999999998, 0.4482507, 0.661141, -0...  
2      [0.07080416111111111, 0.3336016666666666, 0.40...  
3      [-0.1415063259259259, 0.20625797777777777, 0.3...  
4      [-0.10033871904761904, 0.31728433333333333, 0....  
...                                                  ...  
29995  [-0.12335857142857144, 0.28631307142857143, 0....  
29996  [-0.03749547368421053, 0.14457099999999998, 0....  
29997  [-0.0044482176470588145, 0.27805682352941175, ...  
29998  [-0.07938582307692309, 0.25052637692307694, 0....  
29999  [0.011324695652173911, 0.39018995652173916, 0....  

[30000 rows x 3 columns]

In [ ]:
X_t1=data['vec']
y_t1=data['emotion']

In [ ]:
X_t1=np.concatenate(X_t1,axis=0).reshape(-1,vector_shape)


In [ ]:
X_train_e,X_test_e,y_train_e,y_test_e=train_test_split(X_t1,y_t1,test_size=0.2,random_state=0,stratify=y_t1)

In [ ]:
clf_e=LogisticRegression(solver='liblinear',multi_class='auto')

In [ ]:
clf_e.fit(X_train_e,y_train_e)

LogisticRegression(solver='liblinear')

In [ ]:
y_pred_e=clf_e.predict(X_test_e)

In [ ]:
print(classification_report(y_test_e,y_pred_e))

              precision    recall  f1-score   support

       ANGER       0.63      0.62      0.62      1000
        FEAR       0.72      0.70      0.71      1000
         JOY       0.74      0.73      0.74      1000
        LOVE       0.81      0.83      0.82      1000
     SADNESS       0.75      0.73      0.74      1000
    SURPRISE       0.76      0.80      0.78      1000

    accuracy                           0.74      6000
   macro avg       0.74      0.74      0.74      6000
weighted avg       0.74      0.74      0.74      6000



In [ ]:
#Trying SVM()
clf_s=LinearSVC()
clf_s.fit(X_train_e,y_train_e)
y_pred_s=clf_s.predict(X_test_e)

In [ ]:
print(classification_report(y_test_e,y_pred_s))

              precision    recall  f1-score   support

       ANGER       0.63      0.59      0.61      1000
        FEAR       0.74      0.69      0.72      1000
         JOY       0.73      0.75      0.74      1000
        LOVE       0.81      0.84      0.82      1000
     SADNESS       0.75      0.73      0.74      1000
    SURPRISE       0.76      0.81      0.78      1000

    accuracy                           0.74      6000
   macro avg       0.73      0.74      0.73      6000
weighted avg       0.73      0.74      0.73      6000



In [ ]:
pickle.dump(clf_e,open('model_emotion.pkl','wb'))

In [ ]:
model = pickle.load(open('model_emotion.pkl', 'rb'))
def get_pred(x):
    x = str(x).lower()
    x =  pp.cont_exp(x)
    x =  pp.remove_special_chars(x)
    x = pp.remove_accented_chars(x)
    #x = pp.remove_urls(x)
    #x=pp.make_base(x)
    vec = get_vectors(x).reshape(-1, vector_shape)
    emotion = model.predict(vec)
    return emotion


In [98]:
#print(l)
print(df['twitts'][8])
get_pred(df['twitts'][8])

is happy to have tickets for the concerts


array(['JOY'], dtype=object)

In [ ]:
print(df['twitts'][8])
print(df['sentiment'][8])


is happy to have tickets for the concerts
1


In [ ]:
new_tweet=public_tweets[0].text
print(new_tweet)
get_pred(new_tweet)


The #dollar retreated from a two-week top against its major peers on Thursday as investors trimmed bets that the… https://t.co/3qrTC48W40


array(['SURPRISE'], dtype=object)

In [ ]:
glove_vectors.get('blessed')

array(['0.13434', '0.82289', '-0.33547', '0.17134', '-0.304', '0.43794',
       '-0.49331', '0.35286', '-0.22626', '-0.63663', '-0.0018836',
       '-0.24753', '1.0208', '0.22302', '-0.2165', '-1.1623', '0.09048',
       '0.64609', '-0.91615', '1.0667', '-0.96011', '-0.18434',
       '-0.46175', '-0.093568', '0.14346', '0.33197', '-0.19877',
       '0.50449', '0.065516', '0.04772', '0.33957', '-0.40748', '0.54639',
       '0.21533', '0.35969', '-0.10939', '-0.72263', '0.49397', '0.19877',
       '-0.21124', '0.11769', '0.54988', '1.069', '-0.35561', '0.22211',
       '-0.30089', '0.41206', '0.13876', '0.19043', '-0.055866',
       '-0.53147', '0.21072', '0.89793', '0.12925', '-0.78262', '-1.2799',
       '0.36994', '0.49705', '0.41449', '-0.62019', '0.40722', '0.52996',
       '-0.63554', '-0.90289', '-0.4019', '-0.59956', '0.1665',
       '-0.32778', '0.44646', '-0.86972', '0.62842', '-0.31689',
       '0.21382', '0.058251', '0.70049', '-0.14113', '0.18853',
       '-0.27813', '0.0578

In [ ]:
# Functions to print scores
def training_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act, y_pred), 3)
    #f1 = round(f1_score(y_act, y_pred), 3)
    print(f'Training Scores: Accuracy={acc}')
    
def validation_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act, y_pred), 3)
    #f1 = round(f1_score(y_act, y_pred), 3)
    print(f'Validation Scores: Accuracy={acc}')

NameError: ignored

LinearSVC()